spring.application.name=backend
server.port=${PORT:8080}

# MongoDB Cloud Connection String (Uses Environment Variable in Production)
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://durgesh:durgesh@cluster0.wtvbj5z.mongodb.net/edutrack?retryWrites=true&w=majority}
