spring.application.name=backend
server.port=${PORT:8080}

# MongoDB Cloud Connection String (Uses Environment Variable in Production)
spring.data.mongodb.uri=${MONGODB_URI:mongodb://anushka:anushka@ac-cx3fidr-shard-00-00.9wgty9k.mongodb.net:27017,ac-cx3fidr-shard-00-01.9wgty9k.mongodb.net:27017,ac-cx3fidr-shard-00-02.9wgty9k.mongodb.net:27017/edutrack?ssl=true&replicaSet=atlas-8wqw2t-shard-0&authSource=admin&appName=Cluster0}

# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
